In [2]:
import numpy as np

In [3]:
sarasas = [4, 5, 1, 3, 2]
masyvas = np.array(sarasas)
print(masyvas)

[4 5 1 3 2]


In [4]:
x0 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(x0)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
x0matrix = np.array(x0)
print(x0matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.arange(5, 202, 5))

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200]


In [7]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [8]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
np.linspace(21, 61, 9)

array([21., 26., 31., 36., 41., 46., 51., 56., 61.])

In [11]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
np.random.rand(5)

array([0.94391085, 0.38169355, 0.3655397 , 0.75972008, 0.69417473])

In [13]:
np.random.rand(5, 5)

array([[0.17778033, 0.13937214, 0.52816471, 0.67011862, 0.11415162],
       [0.84220655, 0.38558678, 0.95906165, 0.10736215, 0.81339189],
       [0.67981088, 0.86299151, 0.88336673, 0.11287161, 0.5234152 ],
       [0.74605673, 0.61402921, 0.22879549, 0.44851412, 0.26119299],
       [0.43478751, 0.89849409, 0.1783894 , 0.11825155, 0.1914496 ]])

In [14]:
np.random.randn(4, 4)

array([[-0.63885647, -0.63657529, -1.10199808,  0.12193351],
       [ 0.66152591,  1.35430092, -0.4091311 , -1.49683957],
       [-0.37662153,  0.35296653,  0.48291962,  0.91459572],
       [-0.96312647,  0.01399152,  0.72767466, -2.42169322]])

In [15]:
np.random.randint(1, 100, (5, 5))

array([[67, 48,  6, 48, 77],
       [ 9, 67, 36, 11, 27],
       [12, 55, 31, 86, 62],
       [86, 73, 85,  3, 67],
       [97, 80, 34, 48,  4]])

In [16]:
betko56 = np.random.randint(10, 100, 56)
betko56

array([78, 91, 25, 22, 78, 97, 20, 13, 58, 41, 36, 29, 86, 63, 75, 32, 98,
       33, 57, 51, 11, 92, 17, 54, 99, 72, 34, 28, 37, 53, 51, 21, 52, 78,
       45, 29, 80, 45, 40, 42, 26, 66, 71, 53, 95, 64, 29, 93, 61, 42, 63,
       92, 14, 46, 16, 68])

In [17]:
betko8x7 = betko56.reshape(8, 7)
betko8x7

array([[78, 91, 25, 22, 78, 97, 20],
       [13, 58, 41, 36, 29, 86, 63],
       [75, 32, 98, 33, 57, 51, 11],
       [92, 17, 54, 99, 72, 34, 28],
       [37, 53, 51, 21, 52, 78, 45],
       [29, 80, 45, 40, 42, 26, 66],
       [71, 53, 95, 64, 29, 93, 61],
       [42, 63, 92, 14, 46, 16, 68]])

In [18]:
betko7x8 = betko8x7.transpose()
betko7x8

array([[78, 13, 75, 92, 37, 29, 71, 42],
       [91, 58, 32, 17, 53, 80, 53, 63],
       [25, 41, 98, 54, 51, 45, 95, 92],
       [22, 36, 33, 99, 21, 40, 64, 14],
       [78, 29, 57, 72, 52, 42, 29, 46],
       [97, 86, 51, 34, 78, 26, 93, 16],
       [20, 63, 11, 28, 45, 66, 61, 68]])

In [19]:
betko7x8.reshape(56)

array([78, 13, 75, 92, 37, 29, 71, 42, 91, 58, 32, 17, 53, 80, 53, 63, 25,
       41, 98, 54, 51, 45, 95, 92, 22, 36, 33, 99, 21, 40, 64, 14, 78, 29,
       57, 72, 52, 42, 29, 46, 97, 86, 51, 34, 78, 26, 93, 16, 20, 63, 11,
       28, 45, 66, 61, 68])

In [20]:
daug_betko = np.random.randn(1000, 1000)
print(f"{daug_betko.argmin()}:{daug_betko.min()}, {daug_betko.argmax()}:{daug_betko.max()}")

829083:-5.04763473597665, 764393:4.775467298488


In [21]:
print(daug_betko.shape, daug_betko.dtype)

(1000, 1000) float64


In [22]:
betko10 = np.random.randint(1, 10, 10)
print(betko10)
print(betko10[0], betko10[3], betko10[5:9])

[3 3 8 2 2 2 5 1 7 8]
3 2 [2 5 1 7]


In [23]:
print(betko10[::-1])

[8 7 1 5 2 2 2 8 3 3]


In [24]:
print(betko10[-3:5:-1])

[1 5]


In [25]:
betko10[::2] = 0
print(betko10)

[0 3 0 2 0 2 0 1 0 8]


In [26]:
betko7x7 = betko7x8[:, :7]
print(betko7x7, betko7x7.shape, betko7x7[3, 3])

[[78 13 75 92 37 29 71]
 [91 58 32 17 53 80 53]
 [25 41 98 54 51 45 95]
 [22 36 33 99 21 40 64]
 [78 29 57 72 52 42 29]
 [97 86 51 34 78 26 93]
 [20 63 11 28 45 66 61]] (7, 7) 99


In [27]:
print(betko7x7[2:5, 2:5])

[[98 54 51]
 [33 99 21]
 [57 72 52]]


In [28]:
senukai = betko7x7 >= 50
print(senukai)

[[ True False  True  True False False  True]
 [ True  True False False  True  True  True]
 [False False  True  True  True False  True]
 [False False False  True False False  True]
 [ True False  True  True  True False False]
 [ True  True  True False  True False  True]
 [False  True False False False  True  True]]


In [29]:
print(betko7x7[senukai], betko7x7[senukai].shape)

[78 75 92 71 91 58 53 80 53 98 54 51 95 99 64 78 57 72 52 97 86 51 78 93
 63 66 61] (27,)


In [30]:
betko7x7[betko7x7 < 50], betko7x7[betko7x7 < 50].shape

(array([13, 37, 29, 32, 17, 25, 41, 45, 22, 36, 33, 21, 40, 29, 42, 29, 34,
        26, 20, 11, 28, 45]),
 (22,))

In [31]:
betko7x7[2:5, 2:5] = 77
print(betko7x7)

[[78 13 75 92 37 29 71]
 [91 58 32 17 53 80 53]
 [25 41 77 77 77 45 95]
 [22 36 77 77 77 40 64]
 [78 29 77 77 77 42 29]
 [97 86 51 34 78 26 93]
 [20 63 11 28 45 66 61]]


In [32]:
betko8x7

array([[78, 91, 25, 22, 78, 97, 20],
       [13, 58, 41, 36, 29, 86, 63],
       [75, 32, 77, 77, 77, 51, 11],
       [92, 17, 77, 77, 77, 34, 28],
       [37, 53, 77, 77, 77, 78, 45],
       [29, 80, 45, 40, 42, 26, 66],
       [71, 53, 95, 64, 29, 93, 61],
       [42, 63, 92, 14, 46, 16, 68]])

In [33]:
septyni7 = betko7x7[2:5, 2:5].copy()
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [34]:
betko7x7[2:5, 2:5] = np.random.randint(10, 100, (3, 3))
betko7x8

array([[78, 13, 75, 92, 37, 29, 71, 42],
       [91, 58, 32, 17, 53, 80, 53, 63],
       [25, 41, 15, 30, 35, 45, 95, 92],
       [22, 36, 52, 73, 83, 40, 64, 14],
       [78, 29, 70, 75, 77, 42, 29, 46],
       [97, 86, 51, 34, 78, 26, 93, 16],
       [20, 63, 11, 28, 45, 66, 61, 68]])

In [35]:
septyni7

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

# Matematika

In [36]:
simtukai = septyni7 + 23
print(simtukai)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [37]:
simtukai += 23
simtukai

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [38]:
simtukai + septyni7

array([[200, 200, 200],
       [200, 200, 200],
       [200, 200, 200]])

In [39]:
simtukai / septyni7

array([[1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026],
       [1.5974026, 1.5974026, 1.5974026]])

In [40]:
random77 = betko7x7 ** np.random.randint(2, 10, (7, 7))
random77[:, :3]

array([[        474552,      815730721, 13348388671875],
       [          8281,         195112,          32768],
       [     244140625,      115856201,      170859375],
       [           484,        1679616,    19770609664],
       [          6084,            841,     1680700000],
       [  832972004929,   404567235136,           2601],
       [      64000000,    62523502209,           1331]])